#!/usr/bin/env bash

echo "[GHOSTTY] Rebuilding the config file"

cp config config.bak
exec >config

cat <<-EOF
# Config autogenerated. The changes in this file can go lost since
# the configuration is generated by the build.sh

EOF

cat base.config

os_version="$(uname -s)"

echo ''

if [[ -f osx.config ]] && [[ "$os_version" == "Darwin" ]]; then
    cat osx.config
fi

if [[ -f linux.config ]] && [[ "$os_version" == "Linux" ]]; then
    cat linux.config
fi
