#!/usr/bin/env bash

CONFIG_FILE='aerospace.toml'

[[ -f $CONFIG_FILE ]] && old_md5=$( md5sum $CONFIG_FILE )

cat > aerospace.toml <<EOT
###   This file is generated by the .config/aerospace/build.sh any changes are going to be lost
###    at the next execution.

EOT
cat *__*.toml >> aerospace.toml

[[ -f $CONFIG_FILE ]] && new_md5=$( md5sum $CONFIG_FILE )

if [[ "$old_md5" == "$new_md5" ]] ; then
    echo "[AeroSpace] No changes found"
else
    echo "[AeroSpace] Changes found. Config rebuilt"
fi

if hash aerospace ; then
    aerospace reload-config
fi
